### ISSUE TITLE
Breyta útfærslu á eindaga

### ISSUE THREAD

**Issue by midran** [stadlar/GRV-TS236-BIS#1]
= = = 
Í framhaldi af inngöngu Íslands í PEPPOL á næstu dögum þarf að endurskoða TS236 sem mun leiða til þess að það þarf að gefa út nýja útgáfu af tækniforskrift.  Breytt fyrirkomulag á eindaga sem FUT/GRV hefur samþykkt verður fellt inn í þessu næstu útgáfu, sem taka mun gildi 1. maí. 

Bent er á að hægt að innleiða nýtt fyrirkomulag á eindaga strax. Breytingar á reglum, schematron, verða að nýjar reglur fara inn strax, en stuðningur við eldra fyrirkomulag eindaga verður áfram til staðar í reglunum fram á næsta vor. Íslenskar reglur verða síðan felldar inn í PEEPOL schematrons frá og með 1.maí.  PEPPOL schematron munu taka alfarið við frá og með 1.maí 2021.

Bent er á þeir sem taka inn haust útgáfu frá PEPPOL 2020 þurft að gæta þess að eldra fyrirkomulag á eindaga fellur út 1.nóvember. 

Allar athugasemdir skal senda á ritara nefndarinnar, 
kveðja

= = = Breyting sem samþykkt hefur verið af FUT/GRV er eftirfarandi: 

CEN nefndin TS434 hefur gert breytingar á viðskiptareglum þannig að útfærsla FUT/GRV á eindaga mun hætta að virka. 
TS236 lýsir eindaga sem: 
![eindagiA](https://user-images.githubusercontent.com/4922787/131885448-4184be04-4ab5-40c6-b1a5-397bedd1a832.jpg)

Tækninefnd FUT-GRV hefur samþykkt að gerð verði eftirfarandi breyting á framsetningu:
![eindagiB](https://user-images.githubusercontent.com/4922787/131885447-86f1f5b0-85c1-488b-8b4e-c61731106e8d.jpg)

**Comment by midran** [comment]
Samþykkt til framkvæmdar 2021-08-19

**Comment by stadlar** [comment]
Samkvæmt fundi TN-GRV-220329 er þessu verkþætti lokið
